// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHx5DwNAOPcdxJ6xeMkxSPM6nZ7lwmkkM',
    appId: '1:234025044437:android:ee8a4432b3fa9b92cc955c',
    messagingSenderId: '234025044437',
    projectId: 'grow-mate-252dd',
    storageBucket: 'grow-mate-252dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqscmMdzJShE2oiA4OvOZIWMKP98jHIxo',
    appId: '1:234025044437:ios:60c87f8838f24a2acc955c',
    messagingSenderId: '234025044437',
    projectId: 'grow-mate-252dd',
    storageBucket: 'grow-mate-252dd.firebasestorage.app',
    iosBundleId: 'com.example.growMateVersion2',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkZJNXGgXBfPXgVsKLXhtQGNt5d_z3Zrg',
    appId: '1:234025044437:web:7c9b42c8aab40b33cc955c',
    messagingSenderId: '234025044437',
    projectId: 'grow-mate-252dd',
    authDomain: 'grow-mate-252dd.firebaseapp.com',
    storageBucket: 'grow-mate-252dd.firebasestorage.app',
    measurementId: 'G-6KRHMQP485',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqscmMdzJShE2oiA4OvOZIWMKP98jHIxo',
    appId: '1:234025044437:ios:60c87f8838f24a2acc955c',
    messagingSenderId: '234025044437',
    projectId: 'grow-mate-252dd',
    storageBucket: 'grow-mate-252dd.firebasestorage.app',
    iosBundleId: 'com.example.growMateVersion2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkZJNXGgXBfPXgVsKLXhtQGNt5d_z3Zrg',
    appId: '1:234025044437:web:9fd3b1541f7d0d96cc955c',
    messagingSenderId: '234025044437',
    projectId: 'grow-mate-252dd',
    authDomain: 'grow-mate-252dd.firebaseapp.com',
    storageBucket: 'grow-mate-252dd.firebasestorage.app',
    measurementId: 'G-V70YKGMEJ6',
  );

}